hienphap: "Hiến pháp"
luat: "Luật"
boluat: "Bộ luật"
phaplenh: "Pháp lệnh"
nghiquyet: "Nghị quyết"
nghiquyetlientich: "Nghị quyết liên tịch"
lenh: "Lệnh"
quyetdinh: "Quyết định"
nghidinh: "Nghị định"
thongtu: "Thông tư"
thongtulientich: "Thông tư liên tịch"
chithi: "Chỉ thị"
huongdan: "Hướng dẫn"
kehoach: "Kế hoạch"
congdien: "Công điện"
congvan: "Công văn"
vanban: "Văn bản"
saclenh: "Sắc lệnh"
dieuuocquocte: "Điều ước quốc tế"
hiepdinh: "Hiệp định"
